# Generated by Django 5.1 on 2024-09-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_booking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_completed",
            field=models.BooleanField(default=False),
        ),
    ]
